/**
 * Writes the committed case data.
 *
 * Enumerates the 57 orientation classes from combinatorics, binds each to its
 * standard number by inverting a hand-entered canonical algorithm, and refuses
 * to write anything unless every check in `verify-cases.ts` passes.
 *
 * Run: pnpm data:cases
 */

import { writeFileSync } from 'node:fs'

import { patternKey } from '../src/core/pattern'
import { bindCases, VerificationError } from './verify-cases'

function render(cases: ReturnType<typeof bindCases>): string {
  const entries = cases
    .map(
      (c) => `  {
    id: ${c.id},
    name: ${JSON.stringify(c.name)},
    group: ${JSON.stringify(c.group)},
    pattern: patternFromKey('${patternKey(c.pattern)}'),
    alg: ${JSON.stringify(c.alg)},
  },`,
    )
    .join('\n')

  return `// GENERATED by scripts/enumerate-cases.ts — do not edit by hand.
//
// Patterns come from the combinatorial enumeration in src/core/pattern.ts;
// numbers, names and algorithms come from scripts/oll-algorithms.ts. The two
// are cross-checked against each other before this file is written, and again
// in src/core/data/data.test.ts.

import { patternFromKey } from '../pattern'
import type { OllCase } from '../types'

export const CASES: readonly OllCase[] = [
${entries}
]

export const CASES_BY_ID: ReadonlyMap<number, OllCase> = new Map(CASES.map((c) => [c.id, c]))
`
}

try {
  const cases = bindCases()
  writeFileSync('src/core/data/cases.ts', render(cases), 'utf8')
  console.log(`Wrote src/core/data/cases.ts (${cases.length} cases).`)
} catch (error) {
  if (error instanceof VerificationError) {
    console.error('Refusing to write case data:' + error.message)
    process.exitCode = 1
  } else throw error
}
